export interface Establishment {
    nombre:string,
    radioActive:string,
    recommended:boolean,
    precioSinPase:string,
    descripcionES:string,
    descripcionEN:string,
    descripcionDE:string,

    aperturaMañanaLunes: string,
    cierreMañanaLunes: string,
    aperturaTardeLunes: string,
    cierreTardeLunes: string,

    aperturaMañanaMartes: string,
    cierreMañanaMartes: string,
    aperturaTardeMartes: string,
    cierreTardeMartes: string,

    aperturaMañanaMiercoles: string,
    cierreMañanaMiercoles: string,
    aperturaTardeMiercoles: string,
    cierreTardeMiercoles: string,

    aperturaMañanaJueves: string,
    cierreMañanaJueves: string,
    aperturaTardeJueves: string,
    cierreTardeJueves: string,

    aperturaMañanaViernes: string,
    cierreMañanaViernes: string,
    aperturaTardeViernes: string,
    cierreTardeViernes: string,

    aperturaMañanaSabado: string,
    cierreMañanaSabado: string,
    aperturaTardeSabado: string,
    cierreTardeSabado: string,

    aperturaMañanaDomingo: string,
    cierreMañanaDomingo: string,
    aperturaTardeDomingo: string,
    cierreTardeDomingo: string,

    tags: [],
    // ------------- INFORMACION FACTURACION -------------
    cf:string,
    razonSocial:string,
    tlf:string,
    localidad:string,
    calle:string,
    numeroCalle:string,
    cPostal:string,
    email:string,
    iban:string,
    // ------------- INFORMACION PARA EL CLIENTE -------------
    localidadCliente:string,
    cpCliente:string,
    calleCliente:string,
    nCalleCliente:string,
    comunidadCliente:string,
    tlfCliente:string,
    emailCliente:string,
    latitudCliente:string,
    longitudCliente:string,
}
